<a href="https://colab.research.google.com/github/sh-js98/PythorchTuturial/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np


In [ ]:
torch.tensor([[1., -1.], [1., -1.]])
torch.tensor([[1.0000, -1.0000],
              [1.0000, -1.0000]])
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
torch.tensor([[1, 2, 3],
              [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

Create a 2x3 tensor with integer values:text

[[10, 20, 30],
 [40, 50, 60]]

In [ ]:
torch.tensor(np.array([[10, 20, 30],
              [40 , 50, 60]]))

tensor([[10, 20, 30],
        [40, 50, 60]])

Create a 3x3 tensor with floating-point numbers filled with zeros.

In [ ]:
torch.tensor(np.array([[0.0, 0. ,0],
                       [0., 0.00, 0],
                       [0.00, 0.,0]]))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

This is a better way of writing it.

In [ ]:
# Best way (Recommended)
tensor2 = torch.zeros((3, 3))

# Also acceptable
tensor2 = torch.tensor([[0., 0., 0.],
                        [0., 0., 0.],
                        [0., 0., 0.]])

Create a 1D tensor (vector) containing the numbers [5.5, 6.7, 8.1, 9.0].

In [ ]:
torch.tensor(np.array([5.5, 6.7, 8.1, 9.0]))

tensor([5.5000, 6.7000, 8.1000, 9.0000], dtype=torch.float64)

Create a 2x2 tensor from this NumPy array:Pythonimport numpy as np
arr = np.array([[1, 2], [3, 4]], dtype=np.float64)

In [ ]:
torch.tensor(np.array([[1, 2], [3, 4]], dtype=np.float64))

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

torch.zeros() is a very efficient way to create tensors filled with zeros.

Creates a device object that points to the first GPU (if available).
'cuda:0' means GPU number 0.

In [ ]:
torch.zeros([2, 4], dtype=torch.int32)
cuda0 = torch.device('cuda:0')
torch.ones([2, 4], dtype = torch.float64)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

x[1] → selects the second row (index 1, because indexing starts at 0).

x[1][2] → selects the third element (index 2) from that row.

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x[0][1] = 9
print(x)

tensor([[1, 9, 3],
        [4, 5, 6]])


reates a 2D tensor (matrix) with shape (1, 1).
Even though it contains only one number, the double brackets [[1]] make it a 2-dimensional tensor.

In [ ]:
x = torch.tensor([[1]])
x

tensor([[1]])

In [ ]:
x = torch.tensor(2.5)
x

tensor(2.5000)

.item() is a special method that extracts a single value from a tensor and returns it as a standard Python number.
This only works when the tensor contains exactly one element.

In [ ]:
x.item()

2.5

requires_grad=True is the most important part here — it tells PyTorch to track all operations on this tensor for automatic gradient computation (autograd).


out = x.pow(2).sum():
This line creates a computation graph and calculates a scalar value.

x.pow(2) → squares every element → [[1, 1], [1, 1]]
.sum() → adds all elements together → 1 + 1 + 1 + 1 = 4

So out is a scalar tensor containing the value 4.0.

out.backward():

This is the most important line for automatic differentiation.
It computes the gradient of out with respect to all tensors that have requires_grad=True (in this case, x).
PyTorch uses backpropagation (chain rule) to calculate these gradients

x.grad:

Accesses the gradient that was computed and stored in the .grad attribute of tensor x.

out is like the loss.

x is like the weights/parameters.

x.grad tells us: “If you want to decrease out, you should change each value in x by this amount (the gradient).

In [ ]:
x = torch. tensor([[1.0000, -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum()
#It tells us the direction to update x
out.backward()
# This tensor shows how much the final output (out) will change if you slightly increase each value in x.
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

Question 1:

Create a tensor x with the following values:

Python[[2.0, 3.0],

 [4.0, 5.0]]

with requires_grad=True.

Then compute out = x.sum() and run out.backward(). What is x.grad?

In [ ]:
x = torch.tensor([[2.0, 3.0], [4.0, 5.0]], requires_grad=True)
out = x.pow(2).sum()
out.backward()
x.grad

tensor([[ 4.,  6.],
        [ 8., 10.]])

Question 2:

Create a tensor w = torch.tensor([1., 2., 3.], requires_grad=True)

Compute:

Pythonout = (w ** 2).mean()

Run backward and print w.grad.
Explain why you got this gradient.

In [ ]:
w = torch.tensor([1., 2., 3.], requires_grad=True)
out = (w ** 2).mean()
out.backward()
w.grad


tensor([0.6667, 1.3333, 2.0000])

Question 3:

Create this tensor:

Pythonx = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)

Compute out = x.pow(3).sum()

Run out.backward() and show x.grad

In [ ]:
x = torch.tensor([[1.,2], [3.,4.]], requires_grad=True)
out = x.pow(3).sum()
out.backward()
x.grad

tensor([[ 3., 12.],
        [27., 48.]])

Question 3:


Create this tensor:

Pythonx = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)

Compute out = x.pow(3).sum()

Run out.backward() and show x.grad

In [ ]:
x = torch.tensor([[1.,2], [3., 4.]], requires_grad=True)
out = x.pow(3).sum()
out.backward()
x.grad


tensor([[ 3., 12.],
        [27., 48.]])

Question 4 (Slightly Harder):

Create a tensor x of shape (3, 3) filled with ones, with requires_grad=True.

Compute:

Pythonout = (x * x * x).mean()     # or x.pow(3).mean()

After out.backward(), what is x.grad? (Try to predict before running)

In [ ]:
x = torch.ones([3,3], requires_grad=True)
out = (x * x * x).mean()
out.backward()
x.grad

tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])

Question 5:

Create two tensors:

Pythona = torch.tensor(3.0, requires_grad=True)

b = torch.tensor(2.0, requires_grad=True)

Compute loss = (a * b - 10)**2

Run loss.backward() and print both a.grad and b.grad.

In [ ]:
a = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(2.0, requires_grad=True)
out = (a * b -10) **2
out.backward()
a.grad, b.grad



(tensor(-16.), tensor(-24.))

Question 6 (Mini Project Style):

Create a tensor weights of shape (4,) with random values and requires_grad=True.

Then do the following:


Compute output = (weights ** 2).sum()

Run backward

Update the weights using gradient descent:Pythonlearning_rate = 0.1

weights = weights - learning_rate * weights.grad

Print the new weights and run output again (you should see it decreased).

In [8]:
a = torch.rand(4, requires_grad=True)
out = (a ** 2).sum()
out.backward()

learning_rate = 0.1
with torch.no_grad():
 a -= learning_rate * a.grad
print(a)
out = (a ** 2).sum()
print(out)

tensor([0.6314, 0.6407, 0.4956, 0.7482], requires_grad=True)
tensor(1.6147, grad_fn=<SumBackward0>)


Tensor.____init____(self, data) is the old way of creating tensors.

In [9]:
torch.rand(4)


tensor([0.6786, 0.9654, 0.8702, 0.7955])

In [10]:
torch.rand(2,3)

tensor([[0.6733, 0.1448, 0.3810],
        [0.8936, 0.5556, 0.7830]])

torch.randn:                         

Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution).

In [11]:
torch.randn(2,3)

tensor([[-1.6205,  0.8926, -0.0908],
        [-0.3526, -0.1025,  0.9758]])

torch.arange:

torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

Returns a 1-D tensor of size
⌈
end
−
start
step
⌉
⌈
step
end−start
​
 ⌉
 with values from the interval [start, end) taken with common difference step beginning from start.

In [12]:
torch.arange(5)


tensor([0, 1, 2, 3, 4])

In [16]:
#start=0, end, step=1,
torch.arange(2, 26, 4)

tensor([ 2,  6, 10, 14, 18, 22])

Tensor.shape:

Returns the size of the self tensor. Alias for size

In [17]:
t = torch.empty(3, 4, 5)
t.size()

torch.Size([3, 4, 5])

In [18]:
t.shape

torch.Size([3, 4, 5])

torch.numel:

Returns the total number of elements in the input tensor.

In [24]:
a = torch.randn(1, 2, 3, 4, 5)
torch.numel(a)

120

In [25]:
a = torch.zeros(4, 4)
torch.numel(a)

16

torch.reshape(input, shape)

Returns a tensor with the same data and number of elements as input, but with the specified shape. When possible, the returned tensor will be a view of input. Otherwise, it will be a copy. Contiguous inputs and inputs with compatible strides can be reshaped without copying, but you should not depend on the copying vs. viewing behavior.

In [27]:
a = torch.arange(4.)
torch.reshape(a, (2,2))

tensor([[0., 1.],
        [2., 3.]])

In [29]:
b = torch.tensor([[0,1], [2,3]])
torch.reshape(b, (-1,))

tensor([0, 1, 2, 3])

torch.Tensor.view

returns a new tensor with the same data as the self tensor but of a different shape.

In [34]:
x = torch.randn(4, 4)
x.size()

torch.Size([4, 4])

In [40]:
y = x.view(16)
y.size()

torch.Size([16])

torch.Tensor.permute:

Tensor.permute(*dims) → Tensor
Returns a view of the tensor with its dimensions permuted.

In [42]:
x = torch.randn(2, 3, 5)
x.size()


torch.Size([2, 3, 5])

In [43]:
x.permute(2, 0 , 1).size()

torch.Size([5, 2, 3])

torch.squeeze

(input: Tensor, dim: int | List[int] | None) → Tensor
Returns a tensor with all specified dimensions of input of size 1 removed.

In [48]:
x = torch.zeros(2, 9, 1, 2)
x.size()

torch.Size([2, 9, 1, 2])

In [49]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 9, 2])

torch.unsqueeze

(input, dim) → Tensor
Returns a new tensor with a dimension of size one inserted at the speci

In [52]:
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4]])

torch.argmax(input) → LongTensor


Returns the indices of the maximum value of all elements in the input tensor.

In [56]:
a = torch.randn(5, 4)
a

tensor([[-0.4491,  0.9899, -0.1305, -0.5350],
        [-0.9988, -0.5165, -0.3983, -0.4020],
        [-0.1982, -0.1815,  0.2499, -1.7527],
        [-1.2674,  0.1619,  0.1325,  1.4160],
        [-0.3363,  0.3880,  0.1282,  1.6700]])

In [57]:
torch.argmax(a)

tensor(19)

torch.matmul(input, other, *, out=None) → Tensor


Matrix product of two tensors.

In [58]:
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
torch.matmul(tensor1, tensor2).size()
torch.Size([])


torch.Size([])

**Torch Operation exmaples**

1.Create two tensors of shape (3,) and:

Compute their sum:

Compute their element-wise product:

Compute their dot product:

In [59]:
a = torch.rand(3)
b = torch.rand(3)
a + b
a * b
torch.dot(a,b)

tensor(0.4082)

2. Matrix operations

Create a tensor of shape (2, 3) and:

Transpose it using .T:

Verify the new shape:

Multiply it with another compatible tensor:

3. Reshaping

Create a tensor:


x = torch.arange(12).

Reshape it into (3, 4).

Then reshape into (2, 2, 3).

4. Reduction operations

Given:

x = torch.randn(4, 5)
Compute sum of each row
Compute mean of each column:

Find the maximum value in the tensor.

5. Broadcasting

Create:

a = torch.tensor([[1, 2, 3],

                  [4, 5, 6]])

b = torch.tensor([10, 20, 30])

Add a + b using broadcasting

Explain why it works

6. Gradient computation

Create a tensor:

x = torch.rand(5, requires_grad=True)

Compute:

y = (x ** 3).sum()

Run backward

Print gradients

7. Batch matrix transpose

Create a tensor of shape (2, 3, 4):

Use .mT to transpose last two dimensions

Verify the shape

Compare with .T and explain the difference

8. In-place gradient descent

Implement one step of gradient descent:

Create:

w = torch.rand(4, requires_grad=True)

Compute:

loss = (w ** 2).sum()

Backprop

Update weights correctly (no graph break!)

9. Complex tensor + Hermitian

Create a complex tensor:

x = torch.tensor([[1+2j, 3+4j],

                  [5+6j, 7+8j]])
Compute .H

Manually verify:

x.transpose(0,1).conj()

10. Tensor manipulation challenge (important)

Given:

x = torch.arange(24).reshape(2, 3, 4)

Do the following:

Swap last two dimensions

Flatten into 1D

Get only the first “matrix” (index 0)

Compute sum of each row

11. Why does this fail?

a = torch.rand(3, requires_grad=True)

b = a * 2

a = b

b.sum().backward()

print(a.grad)

👉 Explain why a.grad is None