<a href="https://colab.research.google.com/github/sh-js98/PythorchTuturial/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np


In [ ]:
torch.tensor([[1., -1.], [1., -1.]])
torch.tensor([[1.0000, -1.0000],
              [1.0000, -1.0000]])
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
torch.tensor([[1, 2, 3],
              [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

Create a 2x3 tensor with integer values:text

[[10, 20, 30],
 [40, 50, 60]]

In [ ]:
torch.tensor(np.array([[10, 20, 30],
              [40 , 50, 60]]))

tensor([[10, 20, 30],
        [40, 50, 60]])

Create a 3x3 tensor with floating-point numbers filled with zeros.

In [ ]:
torch.tensor(np.array([[0.0, 0. ,0],
                       [0., 0.00, 0],
                       [0.00, 0.,0]]))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

This is a better way of writing it.

In [ ]:
# Best way (Recommended)
tensor2 = torch.zeros((3, 3))

# Also acceptable
tensor2 = torch.tensor([[0., 0., 0.],
                        [0., 0., 0.],
                        [0., 0., 0.]])

Create a 1D tensor (vector) containing the numbers [5.5, 6.7, 8.1, 9.0].

In [ ]:
torch.tensor(np.array([5.5, 6.7, 8.1, 9.0]))

tensor([5.5000, 6.7000, 8.1000, 9.0000], dtype=torch.float64)

Create a 2x2 tensor from this NumPy array:Pythonimport numpy as np
arr = np.array([[1, 2], [3, 4]], dtype=np.float64)

In [ ]:
torch.tensor(np.array([[1, 2], [3, 4]], dtype=np.float64))

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

torch.zeros() is a very efficient way to create tensors filled with zeros.

Creates a device object that points to the first GPU (if available).
'cuda:0' means GPU number 0.

In [ ]:
torch.zeros([2, 4], dtype=torch.int32)
cuda0 = torch.device('cuda:0')
torch.ones([2, 4], dtype = torch.float64)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

x[1] → selects the second row (index 1, because indexing starts at 0).

x[1][2] → selects the third element (index 2) from that row.

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x[0][1] = 9
print(x)

tensor([[1, 9, 3],
        [4, 5, 6]])


reates a 2D tensor (matrix) with shape (1, 1).
Even though it contains only one number, the double brackets [[1]] make it a 2-dimensional tensor.

In [ ]:
x = torch.tensor([[1]])
x

tensor([[1]])

In [ ]:
x = torch.tensor(2.5)
x

tensor(2.5000)

.item() is a special method that extracts a single value from a tensor and returns it as a standard Python number.
This only works when the tensor contains exactly one element.

In [ ]:
x.item()

2.5

requires_grad=True is the most important part here — it tells PyTorch to track all operations on this tensor for automatic gradient computation (autograd).


out = x.pow(2).sum():
This line creates a computation graph and calculates a scalar value.

x.pow(2) → squares every element → [[1, 1], [1, 1]]
.sum() → adds all elements together → 1 + 1 + 1 + 1 = 4

So out is a scalar tensor containing the value 4.0.

out.backward():

This is the most important line for automatic differentiation.
It computes the gradient of out with respect to all tensors that have requires_grad=True (in this case, x).
PyTorch uses backpropagation (chain rule) to calculate these gradients

x.grad:

Accesses the gradient that was computed and stored in the .grad attribute of tensor x.

out is like the loss.

x is like the weights/parameters.

x.grad tells us: “If you want to decrease out, you should change each value in x by this amount (the gradient).

In [ ]:
x = torch. tensor([[1.0000, -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum()
#It tells us the direction to update x
out.backward()
# This tensor shows how much the final output (out) will change if you slightly increase each value in x.
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

Question 1:

Create a tensor x with the following values:

Python[[2.0, 3.0],

 [4.0, 5.0]]

with requires_grad=True.

Then compute out = x.sum() and run out.backward(). What is x.grad?

In [ ]:
x = torch.tensor([[2.0, 3.0], [4.0, 5.0]], requires_grad=True)
out = x.pow(2).sum()
out.backward()
x.grad

tensor([[ 4.,  6.],
        [ 8., 10.]])

Question 2:

Create a tensor w = torch.tensor([1., 2., 3.], requires_grad=True)

Compute:

Pythonout = (w ** 2).mean()

Run backward and print w.grad.
Explain why you got this gradient.

In [ ]:
w = torch.tensor([1., 2., 3.], requires_grad=True)
out = (w ** 2).mean()
out.backward()
w.grad


tensor([0.6667, 1.3333, 2.0000])

Question 3:

Create this tensor:

Pythonx = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)

Compute out = x.pow(3).sum()

Run out.backward() and show x.grad

In [ ]:
x = torch.tensor([[1.,2], [3.,4.]], requires_grad=True)
out = x.pow(3).sum()
out.backward()
x.grad

tensor([[ 3., 12.],
        [27., 48.]])

Question 3:


Create this tensor:

Pythonx = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)

Compute out = x.pow(3).sum()

Run out.backward() and show x.grad

In [ ]:
x = torch.tensor([[1.,2], [3., 4.]], requires_grad=True)
out = x.pow(3).sum()
out.backward()
x.grad


tensor([[ 3., 12.],
        [27., 48.]])

Question 4 (Slightly Harder):

Create a tensor x of shape (3, 3) filled with ones, with requires_grad=True.

Compute:

Pythonout = (x * x * x).mean()     # or x.pow(3).mean()

After out.backward(), what is x.grad? (Try to predict before running)

In [ ]:
x = torch.ones([3,3], requires_grad=True)
out = (x * x * x).mean()
out.backward()
x.grad

tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])

Question 5:

Create two tensors:

Pythona = torch.tensor(3.0, requires_grad=True)

b = torch.tensor(2.0, requires_grad=True)

Compute loss = (a * b - 10)**2

Run loss.backward() and print both a.grad and b.grad.

In [ ]:
a = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(2.0, requires_grad=True)
out = (a * b -10) **2
out.backward()
a.grad, b.grad



(tensor(-16.), tensor(-24.))

Question 6 (Mini Project Style):

Create a tensor weights of shape (4,) with random values and requires_grad=True.

Then do the following:


Compute output = (weights ** 2).sum()

Run backward

Update the weights using gradient descent:Pythonlearning_rate = 0.1

weights = weights - learning_rate * weights.grad

Print the new weights and run output again (you should see it decreased).

In [ ]:
a = torch.rand(4, requires_grad=True)
out = (a ** 2).sum()
out.backward()

learning_rate = 0.1
with torch.no_grad():
 a -= learning_rate * a.grad
print(a)
out = (a ** 2).sum()
print(out)

tensor([0.6314, 0.6407, 0.4956, 0.7482], requires_grad=True)
tensor(1.6147, grad_fn=<SumBackward0>)


Tensor.____init____(self, data) is the old way of creating tensors.

In [ ]:
torch.rand(4)


tensor([0.6786, 0.9654, 0.8702, 0.7955])

In [ ]:
torch.rand(2,3)

tensor([[0.6733, 0.1448, 0.3810],
        [0.8936, 0.5556, 0.7830]])

torch.randn:                         

Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution).

In [ ]:
torch.randn(2,3)

tensor([[-1.6205,  0.8926, -0.0908],
        [-0.3526, -0.1025,  0.9758]])

torch.arange:

torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

Returns a 1-D tensor of size
⌈
end
−
start
step
⌉
⌈
step
end−start
​
 ⌉
 with values from the interval [start, end) taken with common difference step beginning from start.

In [ ]:
torch.arange(5)


tensor([0, 1, 2, 3, 4])

In [ ]:
#start=0, end, step=1,
torch.arange(2, 26, 4)

tensor([ 2,  6, 10, 14, 18, 22])

Tensor.shape:

Returns the size of the self tensor. Alias for size

In [ ]:
t = torch.empty(3, 4, 5)
t.size()

torch.Size([3, 4, 5])

In [ ]:
t.shape

torch.Size([3, 4, 5])

torch.numel:

Returns the total number of elements in the input tensor.

In [ ]:
a = torch.randn(1, 2, 3, 4, 5)
torch.numel(a)

120

In [ ]:
a = torch.zeros(4, 4)
torch.numel(a)

16

torch.reshape(input, shape)

Returns a tensor with the same data and number of elements as input, but with the specified shape. When possible, the returned tensor will be a view of input. Otherwise, it will be a copy. Contiguous inputs and inputs with compatible strides can be reshaped without copying, but you should not depend on the copying vs. viewing behavior.

In [ ]:
a = torch.arange(4.)
torch.reshape(a, (2,2))

tensor([[0., 1.],
        [2., 3.]])

In [ ]:
b = torch.tensor([[0,1], [2,3]])
torch.reshape(b, (-1,))

tensor([0, 1, 2, 3])

torch.Tensor.view

returns a new tensor with the same data as the self tensor but of a different shape.

In [ ]:
x = torch.randn(4, 4)
x.size()

torch.Size([4, 4])

In [ ]:
y = x.view(16)
y.size()

torch.Size([16])

torch.Tensor.permute:

Tensor.permute(*dims) → Tensor
Returns a view of the tensor with its dimensions permuted.

In [ ]:
x = torch.randn(2, 3, 5)
x.size()


torch.Size([2, 3, 5])

In [ ]:
x.permute(2, 0 , 1).size()

torch.Size([5, 2, 3])

torch.squeeze

(input: Tensor, dim: int | List[int] | None) → Tensor
Returns a tensor with all specified dimensions of input of size 1 removed.

In [ ]:
x = torch.zeros(2, 9, 1, 2)
x.size()

torch.Size([2, 9, 1, 2])

In [ ]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 9, 2])

torch.unsqueeze

(input, dim) → Tensor
Returns a new tensor with a dimension of size one inserted at the speci

In [ ]:
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4]])

torch.argmax(input) → LongTensor


Returns the indices of the maximum value of all elements in the input tensor.

In [ ]:
a = torch.randn(5, 4)
a

tensor([[-0.4491,  0.9899, -0.1305, -0.5350],
        [-0.9988, -0.5165, -0.3983, -0.4020],
        [-0.1982, -0.1815,  0.2499, -1.7527],
        [-1.2674,  0.1619,  0.1325,  1.4160],
        [-0.3363,  0.3880,  0.1282,  1.6700]])

In [ ]:
torch.argmax(a)

tensor(19)

torch.matmul(input, other, *, out=None) → Tensor


Matrix product of two tensors.

In [ ]:
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
torch.matmul(tensor1, tensor2).size()
torch.Size([])


torch.Size([])

**Torch Operation exmaples**

1.Create two tensors of shape (3,) and:

Compute their sum:

Compute their element-wise product:

Compute their dot product:

In [ ]:
a = torch.rand(3)
b = torch.rand(3)
a + b
a * b
torch.dot(a,b)

tensor(0.4082)

2. Matrix operations

Create a tensor of shape (2, 3) and:

Transpose it using .T:

Verify the new shape:

Multiply it with another compatible tensor:

In [11]:
a = torch.rand(2,3)
a = a.T
a.shape
b = torch.rand(2)
torch.matmul(a, b)

tensor([0.7048, 0.5437, 0.3611])

3. Reshaping

Create a tensor:


x = torch.arange(12).

Reshape it into (3, 4).

Then reshape into (2, 2, 3).

In [15]:
x = torch.arange(12)
x = x.reshape(3,4)
x = torch.reshape(x, (2,2,3))
print(x)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


4. Reduction operations

Given:

x = torch.randn(4, 5)
Compute sum of each row
Compute mean of each column:

Find the maximum value in the tensor.

In [28]:
x = torch.randn(4, 5)
a = x.sum(dim=1)   # row sums
b = x.mean(dim=0)  # columns mean

# torch.max(input, other) is element-wise comparison, so shapes must match.

maxVal= x.max()

# maxVal = x.max
# This does NOT compute the maximum
# It only stores the function itself, not the result.

print(maxVal)
print(a)
print(b)

tensor(2.0233)
tensor([ 0.2978,  1.3738, -1.4585,  2.8503])
tensor([ 0.8566, -0.0255,  0.5667,  0.4859, -1.1178])


5. Broadcasting

Create:

a = torch.tensor([[1, 2, 3],

                  [4, 5, 6]])

b = torch.tensor([10, 20, 30])

Add a + b using broadcasting

Explain why it works

In [37]:
a = torch.tensor(np.array([[[1,2,3],
                   [4,5,6]]]))
b = torch.tensor(np.array([10,20,30]))
a + b

#import torch

#a = torch.tensor([[1, 2, 3],
  #                [4, 5, 6]])

# b = torch.tensor([10, 20, 30])

# result = a + b
# print(result)



tensor([[[11, 22, 33],
         [14, 25, 36]]])

6. Gradient computation

Create a tensor:

x = torch.rand(5, requires_grad=True)

Compute:

y = (x ** 3).sum()

Run backward

Print gradients

In [39]:
x = torch.rand(5, requires_grad=True)
y = (x ** 3).sum()
y.backward()
x.grad

tensor([1.4091, 1.6801, 2.5109, 1.2885, 2.1307])

7. Batch matrix transpose

Create a tensor of shape (2, 3, 4):

Use .mT to transpose last two dimensions

Verify the shape

Compare with .T and explain the difference

In [46]:
a = torch.rand(2,3,4)
mT = a.mT
print("mTshape: ", mT.shape)
T = a.T
print("Tshape: ", T.shape)

# a   → original (2,3,4)
# mT  → (2,4,3)
# T   → (4,3,2)

mTshape:  torch.Size([2, 4, 3])
Tshape:  torch.Size([4, 3, 2])


/tmp/ipykernel_3458/629738702.py:4: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  T = a.T


8. In-place gradient descent

Implement one step of gradient descent:

Create:

w = torch.rand(4, requires_grad=True)

Compute:

loss = (w ** 2).sum()

Backprop

Update weights correctly (no graph break!)

In [59]:
w =torch.rand(4,requires_grad=True)
loss = (w ** 2).sum()
loss.backward()

## update step
# Imagine you're walking down a hill (loss function):
# Gradient → tells you direction (downhill)
# Learning rate → tells you step size

learning_rate = 0.1

with torch.no_grad():
# W(new) ​= W (old) ​− η⋅∇L
# η (eta) = learning rate
# ∇L = gradient
  w-= learning_rate * w.grad

  # w.grad → stores the gradient of w
  # .zero_() → fills it with zeros (in-place operation)

w.grad.zero_()
# gradients reset to 0
# next backward is clean
# Because PyTorch accumulates gradients by default

tensor([0., 0., 0., 0.])

9. Complex tensor + Hermitian

Create a complex tensor:

x = torch.tensor([[1+2j, 3+4j],

                  [5+6j, 7+8j]])
Compute .H

Manually verify:

x.transpose(0,1).conj()

In [60]:
x = torch.tensor([[1+2j, 3+4j],
                  [5+6j, 7+8j]])
H = x.H
print(H)
print(x.transpose(0,1).conj())

tensor([[1.-2.j, 5.-6.j],
        [3.-4.j, 7.-8.j]])
tensor([[1.-2.j, 5.-6.j],
        [3.-4.j, 7.-8.j]])


10. Tensor manipulation challenge (important)

Given:

x = torch.arange(24).reshape(2, 3, 4)

Do the following:

Swap last two dimensions

Flatten into 1D

Get only the first “matrix” (index 0)

Compute sum of each row

In [10]:
x = torch.arange(24).reshape(2,3,4)
mt = x.mT
flat = torch.flatten(mt)
first_matrix = mt[0]
row_sum = first_matrix.sum(dim=1)
print("flat: ", flat)
print("first_matrix: ", first_matrix)
print("mt: ", mt)
print("row_sum: ", row_sum)

flat:  tensor([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11, 12, 16, 20, 13, 17, 21,
        14, 18, 22, 15, 19, 23])
first_matrix:  tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
mt:  tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])
row_sum:  tensor([12, 15, 18, 21])


11. Why does this fail?

a = torch.rand(3, requires_grad=True)

b = a * 2

a = b

b.sum().backward()

print(a.grad)

👉 Explain why a.grad is None

In [13]:
a = torch.rand(3, requires_grad = True)
b = a * 2
# b is NOT a leaf
# it’s created from an operation
a = b
# overwrote a
# original leaf tensor is lost ❌
# new a is NOT a leaf tensor
b.sum().backward()
print(a.grad)


None


/tmp/ipykernel_1090/3179691432.py:8: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:492.)
  print(a.grad)


12: Create:

x = torch.arange(6)

Reshape it into (2, 3)

In [14]:
x = torch.arange(6)
x = x.reshape(2,3)
print(x)


tensor([[0, 1, 2],
        [3, 4, 5]])


13: Create:

x = torch.arange(8)

Reshape it into (2, 2, 2)

In [15]:
x = torch.arange(8)
x = x.reshape(2,2,2)
print(x)

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])


14: Create:

x = torch.tensor([1,2,3])

Add a dimension at position 0 using unsqueeze

In [16]:
x = torch.tensor([1,2,3])
x = x.unsqueeze(0)
print(x)
# unsqueeze(0) → adds row dimension
# unsqueeze(1) → adds column dimension

tensor([[1, 2, 3]])


15: Create:

x = torch.tensor([[1],[2],[3]])

Remove the extra dimension using squeeze

In [17]:
x = torch.tensor([[1],[2],[3]])
x = x.squeeze()
print(x)
# squeeze(): removes dimension

tensor([1, 2, 3])


16: Create:

x = torch.rand(2,3)

Add a dimension at the end using unsqueeze

In [18]:
x = torch.rand(2,3)
x = x.unsqueeze(-1)
print(x)
# 0 → front
# 1 → middle
# -1 → end

tensor([[[0.4193],
         [0.9844],
         [0.2874]],

        [[0.9981],
         [0.9345],
         [0.8571]]])


17: Create:

x = torch.arange(12).reshape(3,4)

Reshape it into (2,2,3)

In [20]:
x = torch.arange(12).reshape(3,4)
x = x.reshape(2,2,3)
print(x)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


18: Create:

x = torch.rand(2,3,4)

Swap dimensions to (3,2,4) using permute

In [28]:
x = torch.rand(2,3,4)
x = torch.permute(x, (1,0,2))
print(x)

tensor([[[0.1413, 0.5480, 0.3159, 0.5594],
         [0.0574, 0.8127, 0.0710, 0.8902]],

        [[0.8575, 0.8302, 0.9440, 0.5391],
         [0.2471, 0.8861, 0.2280, 0.4922]],

        [[0.0864, 0.1130, 0.6583, 0.7845],
         [0.4235, 0.3541, 0.7950, 0.8841]]])


19: Create:

x = torch.rand(1,3,1,4)

Remove all dimensions of size 1 using squeeze

In [29]:
x = torch.rand(1,3,1,4)
x = x.squeeze()
print(x)
# squeeze(): 	remove ALL dims of size 1
# squeeze(dim):	remove ONLY that dim (if size=1)

tensor([[[[0.2780, 0.9495, 0.3651, 0.8439]],

         [[0.3328, 0.3167, 0.6849, 0.5479]],

         [[0.7390, 0.8223, 0.9358, 0.7002]]]])


20: Create:

x = torch.rand(3,4)

Convert it to shape (1,3,4) using unsqueeze

In [32]:
x = torch.rand(3,4)
x = x.unsqueeze(0)
print(x)

tensor([[[0.4828, 0.0017, 0.6352, 0.1549],
         [0.6645, 0.5897, 0.0597, 0.6665],
         [0.1806, 0.7571, 0.1758, 0.4374]]])


21: Create:

x = torch.arange(24).reshape(2,3,4)

Rearrange dimensions to (4,3,2) using permute

In [33]:
x = torch.arange(24).reshape(2,3,4)
x = torch.permute(x, (2,1,0))
print(x)

tensor([[[ 0, 12],
         [ 4, 16],
         [ 8, 20]],

        [[ 1, 13],
         [ 5, 17],
         [ 9, 21]],

        [[ 2, 14],
         [ 6, 18],
         [10, 22]],

        [[ 3, 15],
         [ 7, 19],
         [11, 23]]])


22: Create:

x = torch.arange(12)

Reshape to (3,4)

Then add a dimension at the front → (1,3,4)

In [34]:
x =torch.arange(12)
x = x.reshape(3,4)
x = x .unsqueeze(0)
print(x)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])


23: Create:

x = torch.rand(1,2,3)

Remove the first dimension

Then reshape into (3,2)

In [36]:
x = torch.rand(1,2,3)
x = x.squeeze(0)
x = x.reshape(3,2)
print(x)
# x = torch.rand(1,2,3).squeeze(0).reshape(3,2)

tensor([[0.2427, 0.3860],
        [0.2543, 0.6265],
        [0.2328, 0.4126]])


24: Create:

x = torch.arange(24).reshape(2,3,4)

Permute to (3,4,2)

Then reshape to (3,8)

In [41]:
x = torch.arange(24).reshape(2,3,4)
x = torch.permute(x, (1,2,0))
x = x.reshape(3,8)
print(x)

tensor([[ 0, 12,  1, 13,  2, 14,  3, 15],
        [ 4, 16,  5, 17,  6, 18,  7, 19],
        [ 8, 20,  9, 21, 10, 22, 11, 23]])


25: Create:

x = torch.rand(2,1,3,1)

Squeeze → remove unnecessary dims

Then unsqueeze at dim=1

In [43]:
x = torch.rand(2,1,3,1)
# Removes all dimensions of size 1
x =x.squeeze()
x = x.unsqueeze(1)
print(x)

tensor([[[0.3461, 0.7859, 0.1067]],

        [[0.2905, 0.9689, 0.3022]]])


26: Create:

x = torch.arange(16).reshape(4,4)

Add batch dimension (1,4,4)

Then permute to (4,4,1)

In [7]:
x = torch.arange(16).reshape(4,4)
# unsqueeze(0): Inserts a dimension of size 1 at index 0 (the very beginning)
x = x.unsqueeze(0)
x = torch.permute(x, (1,2,0))
print(x)

tensor([[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]],

        [[12],
         [13],
         [14],
         [15]]])


27: Create:

x = torch.arange(24).reshape(2,3,4)

Flatten to (24,)

Then reshape to (4,6)

In [6]:
x = torch.arange(24).reshape(2,3,4)
x = torch.flatten(x)
x = x.reshape(4,6)
print(x)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])


28: Create:

x = torch.rand(2,3,4)

Permute to (4,2,3)

Then add a dimension at the end

In [9]:
x = torch.rand(2,3,4)
x = torch.permute(x, (2,0,1))
x = x.unsqueeze(-1)
print(x)

tensor([[[[0.8686],
          [0.8837],
          [0.9126]],

         [[0.0581],
          [0.6533],
          [0.8142]]],


        [[[0.1930],
          [0.9406],
          [0.3854]],

         [[0.5715],
          [0.6338],
          [0.0597]]],


        [[[0.5623],
          [0.6677],
          [0.4731]],

         [[0.1342],
          [0.5093],
          [0.6463]]],


        [[[0.8237],
          [0.6518],
          [0.9780]],

         [[0.8458],
          [0.6590],
          [0.0781]]]])


29: Create:

x = torch.rand(1,1,5)

Squeeze all dimensions

Then unsqueeze twice to get (1,5,1)

In [12]:
x = torch.rand(1,1,5)
x = x.squeeze()
x = x.unsqueeze(-1)
x = x.unsqueeze(0)
print(x)

tensor([[[0.2573],
         [0.8429],
         [0.1627],
         [0.3501],
         [0.5395]]])


30: Create:

x = torch.arange(8).reshape(2,2,2)

Permute to (2,2,2) but swap axes
Then reshape to (4,2)

In [17]:
x = torch.arange(8).reshape(2,2,2)
x = torch.permute(x, (0,2,1))
x = x.reshape(4,2)
print(x)

tensor([[0, 2],
        [1, 3],
        [4, 6],
        [5, 7]])


31: Create:

x = torch.arange(48).reshape(2,3,4,2)

Permute to (3,2,4,2)

Squeeze if possible

Then reshape to (3,16)

In [18]:
x = torch.arange(48).reshape(2,3,4,2)
x = torch.permute(x, (1,0,2,3))
x = x.squeeze()
x = x.reshape(3,16)
print(x)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7, 24, 25, 26, 27, 28, 29, 30, 31],
        [ 8,  9, 10, 11, 12, 13, 14, 15, 32, 33, 34, 35, 36, 37, 38, 39],
        [16, 17, 18, 19, 20, 21, 22, 23, 40, 41, 42, 43, 44, 45, 46, 47]])
