<a href="https://colab.research.google.com/github/sh-js98/PythorchTuturial/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np


In [6]:
torch.tensor([[1., -1.], [1., -1.]])
torch.tensor([[1.0000, -1.0000],
              [1.0000, -1.0000]])
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
torch.tensor([[1, 2, 3],
              [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

Create a 2x3 tensor with integer values:text

[[10, 20, 30],
 [40, 50, 60]]

In [8]:
torch.tensor(np.array([[10, 20, 30],
              [40 , 50, 60]]))

tensor([[10, 20, 30],
        [40, 50, 60]])

Create a 3x3 tensor with floating-point numbers filled with zeros.

In [11]:
torch.tensor(np.array([[0.0, 0. ,0],
                       [0., 0.00, 0],
                       [0.00, 0.,0]]))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

This is a better way of writing it.

In [ ]:
# Best way (Recommended)
tensor2 = torch.zeros((3, 3))

# Also acceptable
tensor2 = torch.tensor([[0., 0., 0.],
                        [0., 0., 0.],
                        [0., 0., 0.]])

Create a 1D tensor (vector) containing the numbers [5.5, 6.7, 8.1, 9.0].

In [13]:
torch.tensor(np.array([5.5, 6.7, 8.1, 9.0]))

tensor([5.5000, 6.7000, 8.1000, 9.0000], dtype=torch.float64)

Create a 2x2 tensor from this NumPy array:Pythonimport numpy as np
arr = np.array([[1, 2], [3, 4]], dtype=np.float64)

In [15]:
torch.tensor(np.array([[1, 2], [3, 4]], dtype=np.float64))

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

torch.zeros() is a very efficient way to create tensors filled with zeros.

Creates a device object that points to the first GPU (if available).
'cuda:0' means GPU number 0.